### ISSUE TITLE
Reel adapter/tests seam to be broken

### ISSUE THREAD

**Issue by Asmod4n** [webmachine/webmachine-ruby#230]
@tarcieri if you got time, might you try to take a look at why all reel specs are failing?

**Comment by bethesque** [comment]
:+1:

**Comment by tarcieri** [comment]
No idea, looks like it might be related to upstream Celluloid changes /cc @digitalextremist

**Comment by jimvm** [comment]
This is the culprit:
```ruby
@server = ::Reel::Server::HTTP.supervise(@options[:host], @options[:port], &method(:process))
```
See [here](https://github.com/webmachine/webmachine-ruby/blob/master/lib/webmachine/adapters/reel.rb#L33).

Running the specs with the latest Celluloid version gives you a deprecation warning:
```
INFO -- : Celluloid 0.17.1.1 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
```

[See the link](http://git.io/vJf3J). The supervise method call needs to be updated. The host and port options need to be put in an array in an :args options hash but it's not clear to me where the callback method goes.

On the other hand, using `::Reel::Server::HTTP.new` instead of `.supervise` gets the specs green again. It can handle the host, port, and callback arguments. Maybe we can go with that?

I assume that the HTTPS path needs to be updated as well. But when I got the HTTP path passing again, I did not get any failing specs for the HTTPS path.

Also, there are spec files in the lib directory. Do they belong there or can they be moved?

**Comment by digitalextremist** [comment]
@jimvm is right that the API is different, requiring `args: []` but there is also an issue reported about preserving blocks passed in, as questioned above: https://github.com/celluloid/celluloid-supervision/issues/24 ... Will resolve the `celluloid-supervision` block clobbering piece and recut that gem.

**Comment by Asmod4n** [comment]
@seancribbs was there a reason the adapter_lint isn't in the spec folder? I found it a bit confusing too.

**Comment by samwgoldman** [comment]
@Asmod4n The idea is that those spec files can be used by 3rd party adapters, to verify conformance. At some point in the distant past, we wanted to extract all the adapters into separate gems.

**Comment by Asmod4n** [comment]
Yes, right. Thats actually a very good idea.

**Comment by jimvm** [comment]
Would it be difficult to extract them into separate gems?

**Comment by rgarner** [comment]
It'd be great to extract them into separate gems – it's busy looking like fixing the build for webmachine-ruby tends to get stalled because it's difficult to make five adapters based on differing concurrency models run consistently across half a dozen rubies.

I've had a stab at addressing some of this *without* extracting gems for now in #233. Just `require`ing `celluloid/autostart` before `reel` has the effect of making the reel adapter specs pass again (although it's still reporting running in backported mode for a reason I've not been able to ascertain).

There are a few other fixes in there, notably one for `Socket#close` not blocking until the socket's really gone. Does anyone feel inclined to review?

**Comment by bethesque** [comment]
Sounds great. On mat leave with twins, sorry, don't have time to review code changes!

**Comment by rgarner** [comment]
Woah, congrats and good heavens, @bethesque. I'm surprised you have time to *breathe*, let alone reply!

**Comment by bethesque** [comment]
One handed typing while they sleep!
